### ISSUE TITLE
Finding first six test users

### ISSUE THREAD

**Issue by chartgerink** [libscie/liberate-science#4]
**NOTE: Testing phase not yet open! We are still in active development of the prototype.**

Hi everyone,

You have probably been linked here to get more information on becoming a test user (if you stumbled here on your own: 🙇). Thanks for being here and spending time on this project 💕 

We are looking for 6 semi-technical people to help do a first test-run of a decentralized scholarly communication platform. Do not worry, we will guide you along the way and have a Rapid Response Plan (which is a FAQ but sounds more epic) in place for testers 💯 We will try to make testing and providing feedback as easy as possible.

If you feel uncomfortable testing at an early stage, please sign up for the newsletter at [libscie.org](http://libscie.org/) and you will be first to know when a later, less technical stage opens up.

# Requirements

Interested in testing out this prototype with us? Please check the following requirements first before replying.

* You are actively doing empirical research and are making some form of progress on a project/project(s) in the next three months (February 5, 2018 - May 7, 2018).
* You are okay with sharing preliminary versions of your work and data openly and have agreement of your collaborators to do so (sorry, we will tackle issues of non-shareable data at a later time!).
* You communicate in English, Dutch, or are willing to accept my limited German responses (sorry, limited support for other languages because I'll be supporting the first round)
* You are not from the geographic region or field of one of the other testers (we want to test in a diverse way).
* You will respect the Code of Conduct of this project.
* You are able to commit one hour of testing per week for twelve weeks (this includes testing the platform, providing asynchronous feedback, or hopping on calls to chat about your experience).

# Testers

- [x] Tester 1 - @pederisager (Europe)
- [x] Tester 2 - @ametodico (South America)
- [x] Tester 3 - VickySteeves (North America)
- [x] Tester 4 - kamel2017 (Africa)
- [x] Tester 5 - dasaptaerwin (Asia/Pacific)
- [x] Tester 6 - stuartyeates (Oceanic)

# Boilerplate testing agreement

If you want to help test and agree with the requirements, please copy-paste the following boilerplate text, replace the square brackets and send it to chris@libscie.org. Please take into account that your GitHub account could identify you and if you wish to remain anonymous, you should make a separate GitHub account for the testing phase.

> I, [GITHUB_HANDLE], agree to test the Liberate Science decentralized scholarly communication platform for one hour per week, over the course of twelve weeks. I will respect the code of conduct as specified in the GitHub repository and understand that

**Comment by chartgerink** [comment]
Found first two testers: @ametodico and @pederisager! This would mean we have two continents represented already for testing!

Could you both please go through the issue OP above and provide me with comments/questions/affirmations if you have any? 🍉

**Comment by pederisager** [comment]
Hi Chris! 
Slightly concerned about whether I am qualified to be an early stage tester since, due to the nature and stage of my PhD, I cannot guarantee that I will be doing empirical research (i.e. generating new data) in the specified period. I am currently drafting the plan for the first year of the PhD. I can get back to you regarding specific projects I would be working on when the draft is done to see if they fit your requirements!

**Comment by chartgerink** [comment]
@pederisager no worries! All kinds of content generating work would fit, so also theory, hypotheses and what not. This infrastructure would make anything *you* find worth sharing the unit of content and give you the power to share it when you want, so unless you feel you have nothing worthwhile to share I'd say stick around for testing? 💟

**Comment by pederisager** [comment]
Glad to hear, then I will be sticking around!

**Comment by chartgerink** [comment]
Pinging the testers for round 1 for this announcement: Due to changes in the software development timetable the testing timetable has been adjusted as well. I am doing my best to let testing start as soon as possible, but will be postponed indefinitely for now. If you want to rescind your testing offer, I fully understand and I am really sorry testing cannot start at the beginning of February. I will keep you posted here.

- [x] Tester 1 - @pederisager (Europe)
- [x] Tester 2 - @ametodico (South America)
- [x] Tester 3 - @VickySteeves (North America)
- [x] Tester 4 - @kamel2017 (Africa)
- [x] Tester 5 - @dasaptaerwin (Asia/Pacific)
- [x] Tester 6 - @stuartyeates (Oceanic)

**Comment by ametodico** [comment]
Hey Chris. I DO NOT WANT TO RESCIND :P,  im still interested and will be waiting for news :)

**Comment by pederisager** [comment]
Hey Chris!

Also still interested, and actually do not mind that testing will be
delayed slightly O:)


Cheers
Peder

2018-01-15 15:30 GMT+01:00 Ricardo Hartley <notifications@github.com>:

**Comment by kamel2017** [comment]
Hi Chris,
I am very sorry, I am away from my desk till 19th of January. I'II
participate to International conference.
With best regards
Kamel

Le 15 janv. 2018 15:26, "Chris Hartgerink" <notifications@github.com> a
écrit :

**Comment by VickySteeves** [comment]
Hi Chris! That's fine with me! Happy to test whenever you're ready!

**Comment by chartgerink** [comment]
Okay, I'm finally able to update this conversation :confetti_ball:

After receiving funding (!), we're now on track to make a first implementation of the *command line tool*. Testing is projected to be possible from December onward based on the roadmap we're working with now. The application is renamed to Hypergraph, and Liberate Science is the organization building it.

I do not want to assume you're interested, so please let me know through the link below if you are :) I'll be sure to get the relevant information to you when we start testing. Feel free to forward this link to anyone you think might be interested as well!

https://chrishartgerink.typeform.com/to/VNfDMq
